server:
  port: 8090
spring:
  application:
    name: microservice-proxy
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    microservice-discovery:
      path: /microservice-discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
    payment:
      path: /payment/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8080
    payment-validation:
      path: /payment-validation/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8081

