server:
  port: 8081

spring:
  application:
    name: payment-validation
  datasource:
    url: jdbc:postgresql://validationdb:5434/validation
    username: validation
    password: validation
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: public
    table: schema-history
    baselineOnMigrate: true
    out-of-order: true
    ignore-missing-migrations: true
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: payment-validation0
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    registryFetchIntervalSeconds: 5

axon:
  kafka:
    client-id: validation-client
    default-topic: general_event_topic
    consumer:
      group-id: validation-group
      auto-offset-reset: earliest
      bootstrapservers: kafka:9092
    producer:
      retries: 5
      bootstrapservers: kafka:9092
      transaction-id-prefix: validation
  eventhandling:
    processors:
      validation:
        source: kafkaMessageSource
        mode: TRACKING
        threadCount: 1
        batchSize: 1
  distributed:
    enabled: true
